Bump required JDK version
eclipse-ee4j/jaxr-ri pull request #6
Opened 2019-09-13 18:59 UTC by pzygielo

2019-09-13 22:19 UTC, bshannon requested changes
There's no reason this *needs* JDK 11.
A better fix would be to remove the &lt;release> configuration in the compiler plugin
and allow it to build with JDK 8.

2019-09-14 05:58 UTC, pzygielo commented
> A better fix would be to remove the <release> configuration in the compiler plugin
> and allow it to build with JDK 8.

Strange, but with `openjdk version "11.0.4" 2019-07-16` I do not observe problem reported/solved in #2 indeed.
So - `release` configuration removed and buildability with JDK8 restored.
As [jenkins:jaxr-ri-release](https://jenkins.eclipse.org/metro/job/jaxr-ri-release) uses `JAVA_HOME=/opt/tools/java/openjdk/jdk-11/latest` it shall be no problem on CI.

2019-09-14 06:01 UTC, pzygielo commented
> Strange, but with `openjdk version "11.0.4" 2019-07-16` I do not observe problem reported/solved in #2 indeed.
But I do - with 82d0295 reverted (ie. with source/target set again).

2019-09-14 06:35 UTC, bshannon approved these changes

2019-09-14 06:36 UTC, merged